export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const FETCH_CARS_START = 'FETCH_CARS_START'
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS'
export const FETCH_CARS_FAIL = 'FETCH_CARS_FAIL'

export const RENT_CAR_START = 'RENT_CAR_START'
export const RENT_CAR_SUCCESS = 'RENT_CAR_SUCCESS'
export const RENT_CAR_FAIL = 'RENT_CAR_FAIL'
export const RENT_TOGGLE_MODAL = 'RENT_TOGGLE_MODAL'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'

export const FROM_DATE = 'FROM_DATE'
export const TO_DATE = 'TO_DATE'
export const UPDATE_TOTAL_PRICE = 'UPDATE_TOTAL_PRICE'
export const RENT_HANDLER_ERROR = 'RENT_HANDLER_ERROR'

export const EXTERIOR_IMAGES = 'EXTERIOR_IMAGES'
export const INTERIOR_IMAGES = 'INTERIOR_IMAGES'

export const HISTORY_START = 'HISTORY_START'
export const HISTORY_SUCCESS = 'HISTORY_SUCCESS'
export const HISTORY_FAIL = 'HISTORY_FAIL'

export const NAVIGATIONITEMS = 'NAVIGATIONITEMS'

export const CAR_DETAILS_START = 'CAR_DETAILS_START'

export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS'
export const DELETE_CAR_START = 'DELETE_CAR_START'
export const DELETE_CAR_FAIL = 'DELETE_CAR_FAIL'
export const DELETE_CAR_TOGGLE_MODAL = 'DELETE_CAR_TOGGLE_MODAL'

export const SET_CAR_IMAGE = 'SET_CAR_IMAGE'
export const SET_CAR_NAME = 'SET_CAR_NAME'
export const SET_NEW_CAR_NAME = 'SET_NEW_CAR_NAME'
export const SET_EXTERIOR_IMAGES = 'SET_EXTERIOR_IMAGES'
export const SET_INTERIOR_IMAGES = 'SET_INTERIOR_IMAGES'
export const SET_NEW_PRICE_PERDAY = 'SET_NEW_PRICE_PERDAY'
export const NEW_INTERIOR_IMAGES = 'NEW_INTERIOR_IMAGES'
export const NEW_EXTERIOR_IMAGES = 'NEW_EXTERIOR_IMAGES'
export const NEW_EXTERIOR_IMAGES_FILE_NAME_LENGTH =
  'NEW_EXTERIOR_IMAGES_FILE_NAME_LENGTH'
export const NEW_INTERIOR_IMAGES_FILE_NAME_LENGTH =
  'NEW_INTERIOR_IMAGES_FILE_NAME_LENGTH'
export const SET_PRICE_PERDAY = 'SET_PRICE_PERDAY'
export const SET_BODY_TYPE = 'SET_BODY_TYPE'
export const SET_NEW_BODY_TYPE = 'SET_NEW_BODY_TYPE'
export const SET_CLASS = 'SET_CLASS'
export const SET_NEW_CLASS = 'SET_NEW_CLASS'
export const SET_ENGINE = 'SET_ENGINE'
export const SET_NEW_ENGINE = 'SET_NEW_ENGINE'
export const SET_HORSE_POWER = 'SET_HORSE_POWER'
export const SET_NEW_HORSE_POWER = 'SET_NEW_HORSE_POWER'
